services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "4000:8080"
    environment:
      - ENABLE_OLLAMA_API=False
      - RESET_CONFIG_ON_START=True
      - DEFAULT_USER_ROLE=user
      - DEFAULT_MODELS=mistral
      - ENABLE_OPENAI_API=True
      - WEBUI_SECRET_KEY=superSynthia
      - OPENAI_API_KEY=synthia
      - OPENAI_API_BASE_URL=http://host.docker.internal:5001/v1
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  open-webui-secret:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-secret
    ports:
      - "3000:8080"
    environment:
      - ENABLE_OLLAMA_API=False
      - RESET_CONFIG_ON_START=True
      - DEFAULT_USER_ROLE=user
      - DEFAULT_MODELS=mistral
      - ENABLE_OPENAI_API=True
      - WEBUI_SECRET_KEY=superSynthia
      - OPENAI_API_KEY=synthia
      - OPENAI_API_BASE_URL=http://host.docker.internal:5001/v1
    volumes:
      - open-webui-secret:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  open-webui:

  open-webui-secret: