healthCheckTimeout: 1500 # wait 25 minutes before unhealthy
startPort: 65001 # Ports for containers start at 65001
      
macros:
  "models_directory": /home/oem/Documents/repos/models
  "gpus": "device=0,1,2,3,5"

models:
  "qwen3":
    cmd: |
      docker run --gpus='"${gpus}"' --name qwen-32B
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/Qwen3-32B-Q8_0.gguf
        --gpu-layers 999
        --temp 0.6
        --top-p 0.95
        --min-p 0
        --top-k 20
        --ctx-size 32768
        --api-key synthia
    cmdStop: docker stop qwen-32B
  
  "command-a":
    cmd: |
      docker run --gpus='"${gpus}"' --name command-a
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/CohereForAI_c4ai-command-a-03-2025-Q5_K_M.gguf
        --gpu-layers 999
        --ctx-size 16384
        --temp 0.7
        --top-p 0.95
        --min-p 0.025
        --api-key synthia
    cmdStop: docker stop command-a
    aliases:
      - "synthia:latest"

  "gemma3":
    cmd: |
      docker run --gpus='"${gpus}"' --name gemma3
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/synthia-s1-27b-q8_0.gguf
        --mmproj /models/mmproj-google_gemma-3-27b-it-bf16.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 0.7
        --top_k 40
        --top_p 0.95
        --min_p 0.05
        --repeat-penalty 1.1
        --api-key synthia
    cmdStop: docker stop gemma3

  "silly":
    cmd: |
      docker run --gpus='"${gpus}"' --name silly
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/gemma-3-270m-it-F16.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 1.0
        --top_k 64
        --top_p 0.95
        --min_p 0.0
        --api-key synthia
    cmdStop: docker stop silly

  "silly2":
    cmd: |
      docker run --gpus='"${gpus}"' --name silly2
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/granite-4.0-h-micro-BF16.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 1.0
        --top_k 0
        --top_p 1.0
        --min_p 0.0
        --api-key synthia
    cmdStop: docker stop silly2

  "gpt-oss":
    cmd: |
      docker run --gpus='"${gpus}"' --name gpt-oss
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/gpt-oss-120b-F16.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 1.0
        --top_k 0
        --top_p 1.0
        --min_p 0.0
        --jinja
        --api-key synthia
    cmdStop: docker stop gpt-oss

  "miqu":
    cmd: |
      docker run --gpus='"${gpus}"' --name miqu
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/Midnight-Miqu-103B-v1.5.IQ4_XS.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 0.8
        --top_p 0.95
        --min_p 0.12
        --repeat-penalty 1.05
        --api-key synthia
    cmdStop: docker stop miqu

  "glm45":
    cmd: |
      docker run --gpus='"${gpus}"' --name glm45
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/GLM-4.5-Air-UD-Q6_K_XL.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 0.8
        --top_p 0.95
        --min_p 0.12
        --jinja
        --repeat-penalty 1.05
        --api-key synthia
    cmdStop: docker stop glm45

  "qwen3vl":
    cmd: |
      docker run --gpus='"${gpus}"' --name qwen3vl
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/Qwen3-VL-30B-A3B-Thinking-UD-Q8_K_XL.gguf
        --mmproj /models/mmproj-Qwen3-VL-30B-A3B-Thinking.gguf
        --gpu-layers 999
        --ctx-size 32768
        --temp 0.8
        --top_p 0.95
        --min_p 0.12
        --jinja
        --repeat-penalty 1.05
        --api-key synthia
    cmdStop: docker stop qwen3vl

  "qwen3-next":
    cmd: |
      docker run --gpus='"${gpus}"' --name qwen3-next
        --init --rm -p ${PORT}:8080 -v ${models_directory}:/models ghcr.io/ggml-org/llama.cpp:server-cuda
        --model /models/Qwen3-Next-80B-A3B-Thinking-UD-Q8_K_XL.gguf
        --gpu-layers 999
        --ctx-size 131072
        --temp 0.6
        --top_p 0.95
        --top_k 20
        --min_p 0
        --jinja
        --repeat-penalty 1.05
        --api-key synthia
    cmdStop: docker stop qwen3-next