import json
import os
import typing
import zoneinfo
from datetime import datetime
from typing import Annotated, NotRequired, TypedDict

import openai
from langchain.messages import AIMessage, SystemMessage, ToolMessage
from langchain_core.messages import BaseMessage
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain_tavily.tavily_search import TavilySearch
from langfuse.langchain import CallbackHandler
from langgraph.graph import END, START, StateGraph, add_messages
from langgraph.prebuilt import InjectedState
from openai import AsyncOpenAI
from pydantic import BaseModel

from synthea import memory, rag
from synthea.commands import ParsedArgs
from synthea.config import Config
from synthea.context_manager import DiscordMetadata
from synthea.dtos import GenerationResponse
from synthea.image_generation import ImageModel
from synthea.model import Model
from synthea.openers import OpeningPhraseTracker
from synthea.utilities import inference_logger


class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    memories: str
    system_prompt: str
    current_time: datetime
    day_of_week: str
    model: str  # the name of the model used in the graph
    images: NotRequired[list[bytes]]  # images generated by the agent
    args: ParsedArgs
    discord_metadata: DiscordMetadata


class AgenticModel(Model):
    """Makes requests to an openAI-compatible API.
    """

    def __init__(self):
        synthea_config: Config = Config()
        self.synthea_config = synthea_config

        os.environ["LANGFUSE_PUBLIC_KEY"] = synthea_config.langfuse_public_key
        os.environ["LANGFUSE_SECRET_KEY"] = synthea_config.langfuse_secret_key
        os.environ["LANGFUSE_HOST"] = synthea_config.langfuse_url
        self.langfuse_handler = CallbackHandler()

        self.opening_phrase_tracker = OpeningPhraseTracker()

        # the raw openai handler, used for model queries
        self.openai: AsyncOpenAI = openai.AsyncOpenAI(
            api_key=synthea_config.api_key, base_url=synthea_config.api_base_url,
        )

        self.llm: ChatOpenAI | None = None
        graph = StateGraph(AgentState)
        graph.add_node("memory_retrieval", self.memory_retrieval_node)
        graph.add_node("supervisor", self.supervisor_node)
        graph.add_node("tools", self.tool_node)
        graph.add_node("memory_saver", self.memory_saver_node)

        graph.add_edge(START, "memory_retrieval")
        graph.add_edge("memory_retrieval", "supervisor")
        graph.add_edge(
            "tools", "supervisor",
        )  # loop back to the supervisor once tool calling completes
        graph.add_conditional_edges(
            "supervisor",
            self.should_continue,
            {"use_tool": "tools", "done": "memory_saver"},
        )
        graph.add_edge("memory_saver", END)

        # add the logging callback handler to the graph
        self.agent = graph.compile()

        search_tool = TavilySearch(
            max_results=3,  # how many results to return per search
            search_depth="advanced",  # "basic" is faster, "advanced" is more thorough
            tavily_api_key=synthea_config.tavily_api_key,
        )

        self.tools = [search_tool, generate_image]
        if self.synthea_config.enable_rag_lookup:
            self.tools.append(document_search)

    async def memory_retrieval_node(self, state: AgentState):
        """Retrieves memories from mem0 related to the conversation
        """
        if state["args"].use_as_system_prompt:
            return None
        if self.synthea_config.enable_memory is False:
            return None

        try:
            memories: str = await memory.retrieve_relevant_memories(
                messages=state["messages"], model_name=state["model"],
            )
            return {"memories": memories}
        except Exception as e:
            inference_logger.error("Full traceback: %s", exc_info=True)
            raise e

    async def memory_saver_node(self, state: AgentState):
        """Saves memories related to a conversation to mem0
        """
        if state["args"].use_as_system_prompt:
            return None
        if self.synthea_config.enable_memory is False:
            return None

        try:
            await memory.add_memories(
                messages=state["messages"], model_name=state["model"],
            )
            return {}
        except Exception as e:
            inference_logger.error("Full traceback: %s", exc_info=True)
            raise e

    async def supervisor_node(self, state: AgentState, config: RunnableConfig):
        # custom system prompts often want the bot to be something other than an assistant
        # so don't inject boilerplate in that case
        if state["args"].use_as_system_prompt:
            system = SystemMessage(content=state["system_prompt"])
            response = await self.llm.ainvoke([system] + state["messages"], config)
            return {"messages": [response]}
        # by default, inject boilerplate into the prompt
        opener_string = ""
        if self.opening_phrase_tracker.recent_openers:
            opener_string = "Do not start your response with any of these recently used phrases: \n"
            for opener in self.opening_phrase_tracker.recent_openers:
                opener_string += f'"{opener}..." \n'

        system = SystemMessage(
            content=f"""{state["system_prompt"]} \n \

            {opener_string}

            This chat may include multiple users. Each message includes the user's name at the start, followed by a colon.  

            Current time: {state["current_time"]} ({state["day_of_week"]}) \n \
            What you remember about the user who sent the last message:\n {state["memories"] if state.get("memories") else "Nothing yet."}
            """,
        )
        response = await self.llm.ainvoke([system] + state["messages"], config)
        return {"messages": [response]}

    async def tool_node(self, state: AgentState, config: RunnableConfig):
        last_message: AIMessage = state["messages"][-1]
        results = []
        images = list(state.get("images") or [])

        for tool_call in last_message.tool_calls:
            # sanitize arguments to resolve common failure cases
            # such as quoted strings
            tool_call["args"] = sanitize_args(tool_call["args"])
            tool_fn = {t.name: t for t in self.tools}[tool_call["name"]]

            try:
                result = await tool_fn.ainvoke(tool_call["args"], config=config)
            except Exception as e:
                results.append(
                    ToolMessage(
                        content=f"The tool has encountered an error. You may need to use different arguments, or stop using this tool if the issue cannot be resolved. Tool error: {e}",
                        tool_call_id=tool_call["id"],
                    ),
                )
                continue

            if tool_call["name"] == "generate_image":  # your image tool
                images.append(result)  # stash the URL/path
                results.append(
                    ToolMessage(
                        content="Image generated successfully. It has been added to the 'images' field of the state and will be returned with your final message to the user.",
                        tool_call_id=tool_call["id"],
                    ),
                )
            else:
                results.append(
                    ToolMessage(content=result, tool_call_id=tool_call["id"]),
                )

        return {"messages": results, "images": images}

    async def should_continue(self, state: AgentState):
        last_message = state["messages"][-1]
        if last_message.tool_calls:
            return "use_tool"
        return "done"

    async def queue_for_generation(
        self,
        chat_history: list[BaseMessage],
        args: ParsedArgs = None,
        discord_metadata: DiscordMetadata = None,
        persona_system_prompt: str = None,
    ) -> GenerationResponse:
        """The externally-exposed endpoint to invoke the agentic model.
        """
        synthea_config: Config = Config()
        model_name: str = synthea_config.default_model_name
        if args and args.model:
            model_name = args.model
        model_name = model_name.lower()

        # resolve the reasoning effort: command arg takes precedence, then the
        # model's configured default
        reasoning_effort: str = (
            args.reasoning_effort
            if args and args.reasoning_effort
            else synthea_config.models[model_name].reasoning_effort
        )

        self.llm = ChatOpenAI(
            model=model_name,
            api_key=synthea_config.api_key,
            base_url=synthea_config.api_base_url,
            streaming=True,
            reasoning_effort=reasoning_effort,
        ).bind_tools(self.tools)

        inference_logger.info(
            f"Generating with model {model_name} (reasoning_effort={reasoning_effort})",
        )
        now = datetime.now(tz=zoneinfo.ZoneInfo("America/Los_Angeles"))
        current_time = now.isoformat(timespec="seconds")
        day_of_week = now.strftime("%A")

        state = AgentState(
            messages=chat_history,
            system_prompt=persona_system_prompt,
            current_time=current_time,
            day_of_week=day_of_week,
            model=model_name,
            args=args,
        )

        agent_config: RunnableConfig = {
            "callbacks": [self.langfuse_handler],
            "configurable": {"discord_metadata": discord_metadata},
        }

        result = await self.agent.ainvoke(state, config=agent_config)

        # TODO: parse the response into constituent parts if reasoning was present
        response: GenerationResponse = GenerationResponse(
            final_output=result["messages"][-1].content, images=result.get("images", []),
        )

        # append the
        self.opening_phrase_tracker.record_response(response.final_output)

        return response

    async def get_models(self) -> list[Model]:
        """Sends a prompt to the server for generation. When the server is available,
        it will take up the prompt and generate a response.
        """
        models = await self.openai.models.list()
        return models.data


@tool
async def generate_image(prompt: str, width: int, height: int) -> bytes:
    """Generates an image. This is an expensive operation, so this
    tool should be used only when highly relevant to the conversation.

    Use a long, highly detailed, and descriptive prompt when using this tool.
    """
    image_model: ImageModel = ImageModel()
    inference_logger.info(f"Generating image with prompt: {prompt}")
    response = await image_model.generate_image_from_prompt(
        positive_prompt=prompt, width=width, height=height,
    )

    # this tool generates one image at a time, so return that image
    for node_id in response:
        for image_data in response[node_id]:
            return image_data


class DocumentSearchInput(BaseModel):
    query: str


@tool
async def document_search(
    query: str,
    config: RunnableConfig,
    require: str | list[str] | None = None,
    exclude: str | list[str] | None = None,
    regex: str | None = None,
) -> str:
    """Retrieves documents from the document store. Use this before searching the internet
    with other tools.
    ALWAYS use this tool when the user asks about anything that could be
    in their uploaded documents. Use it for ANY question about specific facts,
    details, policies, data, or content — do not answer from memory if this
    tool might have the answer.

    Args:
        query:   The search query to find relevant documents.
        require: A term or list of terms that MUST appear in results (case-sensitive).
                 ALWAYS set this when the user mentions a specific name, place, product,
                 or proper noun. Do NOT retry with a different query alone if results are
                 irrelevant — set require instead.
                 Examples: require="Asteria"  |  require=["Asteria", "Astraea"]
        exclude: A term or list of terms that MUST NOT appear in results. Use to filter
                 out noise when results keep returning irrelevant content.
                 Example: exclude="unrelated_topic"
        regex:   A regex pattern the chunk must match. Use for structured content like
                 emails, dates, IDs, or codes.
                 Example: regex=r"INV-[0-9]+"

    """
    metadata: DiscordMetadata = config["configurable"]["discord_metadata"]
    inference_logger.info(
        f"Retrieving documents with query: {query}"
        + (f", require={require!r}" if require else "")
        + (f", exclude={exclude!r}" if exclude else "")
        + (f", regex={regex!r}" if regex else ""),
    )
    return await rag.retrieve_documents(
        query,
        metadata.guild_id,
        metadata.user_id,
        require=require,
        exclude=exclude,
        regex=regex,
    )


def sanitize_args(args: dict) -> dict:
    sanitized = {}
    for k, v in args.items():
        if isinstance(v, str):
            try:
                parsed = json.loads(v)
                # only unwrap if the result is a primitive, not a dict/list
                if isinstance(parsed, (str, int, float, bool)):
                    sanitized[k] = parsed
                else:
                    sanitized[k] = v
            except (json.JSONDecodeError, ValueError):
                sanitized[k] = v
        else:
            sanitized[k] = v
    return sanitized


def needs_state_injection(tool_fn) -> bool:
    func = getattr(tool_fn, "func", None)
    if func is None:
        return False
    hints = typing.get_type_hints(func, include_extras=True)
    for annotation in hints.values():
        origin = typing.get_origin(annotation)
        if origin is Annotated:
            if any(
                isinstance(a, InjectedState) for a in typing.get_args(annotation)[1:]
            ):
                return True
    return False
