from datetime import datetime, time
from typing import Annotated, List, TypedDict
import zoneinfo

from langchain.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain.tools import tool
from langgraph.graph import StateGraph, START, END, add_messages

from langchain_core.messages import BaseMessage
from langchain_openai import ChatOpenAI
from langchain_tavily.tavily_search import TavilySearch
from langchain_core.runnables import RunnableConfig
from openai import AsyncOpenAI
import openai

from synthea import memory
from synthea.CommandParser import ParsedArgs
from config import Config
from synthea.ImageModel import ImageModel
from synthea.Model import Model
from synthea.dtos.GenerationResponse import GenerationResponse

from ToolUtilities import inference_logger

import os
from langfuse.langchain import CallbackHandler

class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]    
    system_prompt: str
    current_time: datetime
    day_of_week: str
    images: list[bytes] # images generated by the agent

class AgenticModel(Model):
    """
    Makes requests to an openAI-compatible API.
    """

    def __init__(self):
        synthea_config: Config = Config()

        os.environ["LANGFUSE_PUBLIC_KEY"] = synthea_config.langfuse_public_key
        os.environ["LANGFUSE_SECRET_KEY"] = synthea_config.langfuse_secret_key
        os.environ["LANGFUSE_HOST"] = synthea_config.langfuse_url
        self.langfuse_handler = CallbackHandler()

        self.openai: AsyncOpenAI = openai.AsyncOpenAI(
            api_key=synthea_config.api_key,
            base_url=synthea_config.api_base_url
        )

        self.llm: ChatOpenAI | None = None
        graph = StateGraph(AgentState)
        graph.add_node("supervisor", self.supervisor_node)
        graph.add_node("tools", self.tool_node)
        # graph.add_node("formatting", self.formatting_node)
        graph.add_edge(START, "supervisor")
        graph.add_edge("tools", "supervisor") # loop back to the supervisor once tool calling completes
        graph.add_conditional_edges(
            "supervisor",
            self.should_continue,
            {"use_tool": "tools", "done": END}
        )
        # graph.add_edge("formatting", END)


        # add the logging callback handler to the graph
        self.agent = graph.compile()

        search_tool = TavilySearch(
            max_results=3,          # how many results to return per search
            search_depth="basic", # "basic" is faster, "advanced" is more thorough
            tavily_api_key=synthea_config.tavily_api_key
        )
        self.tools = [search_tool, tool(generate_image)]


    async def supervisor_node(self, state: AgentState, config: RunnableConfig):
        system = SystemMessage(content=f"""{state["system_prompt"]} \n \
        Current time: {state["current_time"]} \n \
        Day of week: {state["day_of_week"]} \
        """)
        response = await self.llm.ainvoke([system] + state["messages"], config)
        return {"messages": [response]}

    async def formatting_node(self, state: AgentState, config: RunnableConfig):
        system = SystemMessage(content=f"""Current time: {state["current_time"]} \n \
            Day of week: {state["day_of_week"]} \n \

            You are a formatting agent which rewrites messages. \
            You will be given a message from the user. Your only job is to rewrite it in the voice and style of the character described. Do not respond to the user. Do not add new information. Do not address the user directly. Just rewrite the message content as if the following character had written it: \
            ``` \n \
            {state["system_prompt"]} \n \
            ```""")
        response = await self.llm.ainvoke([system, HumanMessage(content=state["messages"][-1].content)], config)
        return {"messages": [response]}

    async def tool_node(self, state: AgentState):
        last_message: AIMessage = state["messages"][-1]
        results = []
        images = list(state.get("images") or [])

        for tool_call in last_message.tool_calls:
            tool_fn = {t.name: t for t in self.tools}[tool_call["name"]]
            try:
                result = await tool_fn.ainvoke(tool_call["args"])
            except Exception as e:
                results.append(ToolMessage(
                    content=f"Tool error: {e}",
                    tool_call_id=tool_call["id"]
                ))
                continue

            if tool_call["name"] == "generate_image":  # your image tool
                images.append(result)  # stash the URL/path
                results.append(ToolMessage(
                    content="Image generated successfully.",
                    tool_call_id=tool_call["id"]
                ))
            else:
                results.append(ToolMessage(content=result, tool_call_id=tool_call["id"]))

        return {"messages": results, "images": images}
    
    async def should_continue(self, state: AgentState):
        last_message = state["messages"][-1]
        if last_message.tool_calls:
            return "use_tool"
        return "done"


    # @tool
    # def save_memory(content: str) -> str:
    #     """Save important information to long-term memory for future reference."""
    #     result = memory.add(content, user_id=USER_ID)
    #     return f"Saved to memory: {result}"

    # @tool
    # def search_memory(query: str) -> str:
    #     """Search long-term memory for information relevant to the query."""
    #     results = memory.search(query, user_id=USER_ID, limit=5)
    #     if not results:
    #         return "No relevant memories found."
    #     return "\n".join(
    #         f"- {r['memory']} (score: {r['score']:.2f})"
    #         for r in results.get("results", [])
    #     )

    # @tool
    # def list_memories() -> str:
    #     """List all stored memories for the current user."""
    #     results = memory.get_all(user_id=USER_ID)
    #     if not results:
    #         return "No memories stored."
    #     return "\n".join(f"- {r['memory']}" for r in results.get("results", []))

    async def queue_for_generation(self, chat_history: list[dict[str, dict[str, str]]],
                                   args: ParsedArgs = None,
                                   persona_system_prompt: str = None) -> GenerationResponse:
        synthea_config: Config = Config()
        model_name: str = synthea_config.default_model_name
        if args.model:
            model_name = args.model

        self.llm = ChatOpenAI(
            model=model_name,
            api_key=synthea_config.api_key,
            base_url=synthea_config.api_base_url, 
            temperature=0).bind_tools(self.tools)

        # if not synthea_config.models[model_name].vision:
        #     for chat_message in chat_history:
        #         text = ""
        #         for content_part in chat_message["content"]:
        #             if content_part["type"] == "text":
        #                 text += content_part["text"]
        #         chat_message["content"] = text

        inference_logger.info(f"Generating with model {model_name}")
        now = datetime.now(tz=zoneinfo.ZoneInfo("America/Los_Angeles"))
        current_time = now.isoformat(timespec="seconds")
        day_of_week  = now.strftime("%A")

        state = AgentState(
            messages=chat_history,
            system_prompt=persona_system_prompt,
            current_time = current_time,
            day_of_week = day_of_week,
        )

        agent_config: RunnableConfig = {"callbacks": [self.langfuse_handler]}

        result = await self.agent.ainvoke(state, config=agent_config)

        # TODO: parse the response into constituent parts if reasoning was present
        response: GenerationResponse = GenerationResponse(
            final_output=result["messages"][-1].content,
            images=result.get("images", [])
        ) 

        return response
    
    async def get_models(self) -> List[Model]:
        """
        Sends a prompt to the server for generation. When the server is available,
        it will take up the prompt and generate a response.
        """
        models = await self.openai.models.list()
        return models.data

async def generate_image(prompt: str, width: int, height: int) -> bytes:
    """
    Generates an image. This is an expensive operation, so this
    tool should be used only when highly relevant to the conversation.
    
    Use a long, highly detailed, and descriptive prompt when using this tool.
    """
    image_model: ImageModel = ImageModel()
    response = await image_model.generate_image_from_prompt(positive_prompt=prompt, width=width, height=height)

    # this tool generates one image at a time, so return that image
    for node_id in response:
        for image_data in response[node_id]:
            return image_data
